import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';

export const metadata = {
  title: "Web tutorials",
  description: "Generated by ESTSOFT BOOTCAMP",
};

export default function RootLayout({ children }) {
  console.log('공통 레이아웃 실행');
  return (
    <html lang="en">
      <body>        
        <nav className="navbar bg-light">
          <div className="container">
            <h1>
              <Link href="/" className="navbar-brand">WEB</Link>
            </h1>
            <ul className="nav">
              <li className="nav-item"><a href="/read/1" className="nav-link">html</a></li>
              <li className="nav-item"><a href="/read/2" className="nav-link">css</a></li>
              <li className="nav-item"><a href="/read/3" className="nav-link">javascript</a></li>
            </ul>
          </div>
        </nav>
        <main className="container">
          {children}
          <ul className="nav gap-1">
            <li>
              <Link href="/create" className="btn btn-primary">Create</Link>
            </li>
            <li>
              <Link href="/update/1" className="btn btn-secondary">Update</Link>
            </li>
            <li><button type="button" className="btn btn-danger">Delete</button></li>
          </ul>
        </main>
        </body>
    </html>
  );
}
