import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>        
        <nav className="navbar bg-light">
          <div className="container">
            <h1><a href="#" className="navbar-brand">WEB</a></h1>
            <ul className="nav">
              <li className="nav-item"><a href="/read/1" className="nav-link">html</a></li>
              <li className="nav-item"><a href="/read/2" className="nav-link">css</a></li>
              <li className="nav-item"><a href="/read/3" className="nav-link">javascript</a></li>
            </ul>
          </div>
        </nav>
        <main className="container">
          {children}
          <ul className="nav gap-1">
            <li><a href="/create" className="btn btn-primary">Create</a></li>
            <li><a href="/update/1" className="btn btn-secondary">Update</a></li>
            <li><button type="button" className="btn btn-danger">Delete</button></li>
          </ul>
        </main>
        </body>
    </html>
  );
}
